name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate report
        run: npx cypress run --reporter junit --reporter-options "mochaFile=cypress/reports/junit/test-results.[hash].xml"
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**cypress/reports/junit/test-results.[hash].xml'

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: cypress/reports/html
